# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: Ninho de Pombo Obeso
  latitude: !secret address_latitude
  longitude: !secret address_longitude
  elevation: 688.85
  unit_system: metric
  time_zone: America/Sao_Paulo

discovery:
  ignore:
    - yeelight
yeelight:
  devices:
    10.0.0.102: # yeelink-light-color2-miio13444 
      name: Dining Room Light
    10.0.0.100: # yeelink-light-color2-miapbd8a
      name: Office Light
